### ISSUE TITLE
hdkey does not expose a method to get the uncompressed public key

### ISSUE THREAD

**Issue by wighawag** [paulmillr/scure-bip32#11]
Would be great if we could get access to the uncompressed public key.

**Comment by wighawag** [comment]
The ability to provide a uncompressed public key in the constructor or from a static instantiating function would be great too

**Comment by paulmillr** [comment]
`secp.ProjectivePoint.fromHex(compressedPubkey).toRawBytes(false)` would do the conversion for you.

Why do you need specifically uncompressed keys?

**Comment by wighawag** [comment]
Thanks, that works

my use case is to generate ethereum addresses from them

**Comment by paulmillr** [comment]
https://github.com/paulmillr/micro-eth-signer may be useful to you as well

**Comment by MaoHolden** [comment]
Same here, would be great to have access to uncompressed public key and even better to just have access to `get ethAddress`, or is it too high level for this library?

**Comment by paulmillr** [comment]
> would be great to have access to uncompressed public key

What is your use case?

**Comment by MaoHolden** [comment]
Hello @paulmillr thanks for the answer.

I'm using this library in my server to take an XPUB key and generate addresses for my user's without my server having access to the private keys.

so I had to use two libaries 

```js
// SHIB-Shibarium Wallet
import { HDKey } from 'ethereum-cryptography/hdkey.js'
import { Address } from 'micro-eth-signer'
import { wallet } from '../../../../config.js'
// import logger from '../../../../lib/logger.js'

// const log = logger.child({ source: 'shibarium/wallet' })

// create the HD xpub wallet for Shibarium
const shibariumXpubHDWallet = HDKey.fromExtendedKey(wallet.coins.Shibarium.xpub)

/**
 * derive user's public key from the xpub wallet on the server
 * @param {number} userId
 * @returns {String} address
 */
export function generateUserShibariumAddress(userId) {
  // path: /userId/change/index
  const userHDKey = shibariumXpubHDWallet.derive(`m/${userId}`)
  const address = Address.fromPublicKey(userHDKey.publicKey)
  return address
}
```
