### ISSUE TITLE
Possible discrepancy with the cryptocoinjs hdkey lib

### ISSUE THREAD

**Issue by jackson-dean** [paulmillr/scure-bip32#13]
This could be a problem with me and not the lib, but I seem to be getting unexpected results when incrementing the account number portion of the path. I have some code that looks like this:

```ts
    const mnemonic = formControls.mnemonic.value;
    const passphrase = formControls.passphrase.value;
    const accountNumber = Number(formControls.accountNumber.value);
    const masterSeed = mnemonicToSeedSync(mnemonic, passphrase);
    
    const keys = HDKey.fromMasterSeed(masterSeed).derive(`m/44'/0'/${accountNumber}'/0/0`);
 ```
 When I use account number `0`, I get the exact same public key that I get from the cryptocoin hdkey lib. However, if I use any other account number: 1, 2, 3, etc. I do not seem to be seeing the same public key that I get from the other lib. Any ideas where I might be going wrong?

**Comment by paulmillr** [comment]
We have extensive tests. If an output differs between implementations, you can add a failing test:

https://github.com/paulmillr/scure-bip32/blob/main/test/hdkey.test.ts

**Comment by paulmillr** [comment]
i've just compared 400k random seeds with index 2, it all matches.

**Comment by jackson-dean** [comment]
so weird, okay must be something I'm doing weird. thanks man, I will take a closer look at where I'm going wrong.

**Comment by jackson-dean** [comment]
fwiw, I finally found the issue and it is just some weird old code on our side. These libraries are awesome! The lord's work.
