### ISSUE TITLE
Support for ed25519 and NIST P-256 as per SLIP-10

### ISSUE THREAD

**Issue by Mrtenz** [paulmillr/scure-bip32#3]
[SLIP-10](https://github.com/satoshilabs/slips/blob/master/slip-0010.md) describes a way to derive keys from a master seed in a way that is mostly the same as BIP-32, but has support for other curves like ed25519 and NIST P-256 too. It would be great if this was supported by the `@scure/bip32` library.

**Comment by paulmillr** [comment]
https://github.com/paulmillr/ed25519-hdkey
