### ISSUE TITLE
Type check issue

### ISSUE THREAD

**Issue by Unchain68** [paulmillr/scure-bip32#7]
Now I am making my own ethereum wallet for my dapp.
But I found something that may be considered as problematic or it could be considered as a problem because of my lack of blockchain knowledge.
While I was doing a debugging test for my wallet, I found that buffer type checking was not occurring in the process of creating hdwallet connect. 

I set the argument of fromMasterSeed func with seedToHex, not the buffer version.
But, the function generates the value. Even the value was not the same as when the argument  is a buffer type. 

Can you explain about this situation?

**Comment by paulmillr** [comment]
It's hard to understand what you mean. Can you provide some code that describes what happens and where?

**Comment by Unchain68** [comment]
![image](https://user-images.githubusercontent.com/109026317/193245333-bcdb6071-1f4d-46b3-be36-b90517595eea.png)
Buffer type checking didn't occur in here
If the input value is hex form of buffer, but the function made a hdkey

**Comment by paulmillr** [comment]
You are using old insecure version of ethereum-cryptography.

Fixed in [9b268cc](https://github.com/paulmillr/scure-bip32/commit/9b268cc4cb3873c66b2c82cc94b19cdcc25272a8) - will publish a new release in a bit.

**Comment by Unchain68** [comment]
Thanks a lot
